name: Linear Workflow

on:
  workflow_dispatch:

jobs:
  WindowsLinearWorkflow:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Autopkg
        uses: autopkg/setup-autopkg-actions@main

      - name: Run Linear Download Autopkg Recipe
        run: python autopkg/Code/autopkg run -vv Linear/Linear-Win.download.recipe.yaml

