name: Linear Workflow

on:
  workflow_dispatch:

jobs:
  WindowsLinearWorkflow:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up WSL and Ubuntu
        run: |
          wsl --install
          wsl -e sudo apt-get update
          wsl -e sudo apt-get install -y git curl
          wsl -e sudo apt-get install -y autopkg

      - name: Setup Autopkg in WSL
        run: |
          wsl -e autopkg repo-add https://github.com/autopkg/recipes.git
          wsl -e autopkg repo-update all

      - name: Run Linear Download Autopkg Recipe
        run: wsl -e autopkg Linear/Linear-Win.download.recipe.yaml

